/**
 * Project LOOP -- Voice-of-Customer Report PDF Generation
 *
 * Generates professional PDF reports from saved report data using PDFKit.
 */

import PDFDocument from "pdfkit";
import type { VoiceOfCustomerReportContent } from "@/lib/validations/reports";

interface PDFOptions {
  title: string;
  periodLabel: string;
  generatedAt: string;
  generatedBy: string;
  content: VoiceOfCustomerReportContent;
}

export async function generateReportPDF(options: PDFOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "letter",
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        bufferPages: true,
      });

      const chunks: Buffer[] = [];
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      const { title, periodLabel, generatedAt, generatedBy, content } = options;

      // Register fonts (using built-in Helvetica for compatibility)
      doc.font("Helvetica");

      // Header
      doc.fontSize(24).fillColor("#1e293b").text("Project LOOP", { align: "left" });
      doc.moveDown(0.3);
      doc.fontSize(16).fillColor("#6366f1").text("Voice-of-Customer Report", { align: "left" });
      doc.moveDown(0.5);

      // Report metadata
      doc.fontSize(10).fillColor("#64748b");
      doc.text(`Report: ${title}`, { align: "left" });
      doc.text(`Period: ${periodLabel}`, { align: "left" });
      doc.text(`Generated: ${new Date(generatedAt).toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
      })}`, { align: "left" });
      doc.text(`Generated by: ${generatedBy}`, { align: "left" });
      doc.moveDown(1);

      // Divider
      doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(72, doc.y).lineTo(522, doc.y).stroke();
      doc.moveDown(1);

      // Executive Summary
      doc.fontSize(14).fillColor("#1e293b").text("Executive Summary", { underline: true });
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor("#334155").text(content.narrative.executiveSummary, {
        align: "justify",
        lineGap: 4,
      });
      doc.moveDown(1);

      // Statistics Section
      doc.fontSize(14).fillColor("#1e293b").text("Key Statistics", { underline: true });
      doc.moveDown(0.5);

      const stats = content.statistics;
      doc.fontSize(11).fillColor("#334155");
      doc.text(`Total Feedback: ${stats.totalFeedback}`, { continued: true });
      doc.text(`  (${stats.sentimentScoreSampleSize} scored)`, { align: "right" });
      
      if (stats.averageSentimentScore !== null) {
        doc.text(`Average Sentiment Score: ${stats.averageSentimentScore.toFixed(2)}`, { continued: true });
        doc.text(`  (Scale: -1 to +1)`, { align: "right" });
      }

      doc.moveDown(0.5);

      // Sentiment Distribution
      doc.fontSize(12).fillColor("#1e293b").text("Sentiment Distribution");
      doc.moveDown(0.3);
      doc.fontSize(10).fillColor("#334155");
      
      const sentiments = [
        { key: "POS", label: "Positive", color: "#10b981" },
        { key: "NEU", label: "Neutral", color: "#64748b" },
        { key: "NEG", label: "Negative", color: "#f43f5e" },
      ] as const;

      sentiments.forEach((sentiment) => {
        const data = stats.sentimentDistribution[sentiment.key];
        doc.text(`${sentiment.label}: ${data.count} (${data.percentage}%)`);
      });

      doc.moveDown(0.5);

      // Top Themes
      if (stats.topThemes.length > 0) {
        doc.fontSize(12).fillColor("#1e293b").text("Top Themes");
        doc.moveDown(0.3);
        doc.fontSize(10).fillColor("#334155");
        
        stats.topThemes.forEach((theme, index) => {
          doc.text(`${index + 1}. ${theme.name}: ${theme.count} (${theme.percentage}%)`);
        });
        doc.moveDown(1);
      }

      // Divider
      doc.strokeColor("#e2e8f0").lineWidth(1).moveTo(72, doc.y).lineTo(522, doc.y).stroke();
      doc.moveDown(1);

      // AI Narrative Sections
      doc.fontSize(14).fillColor("#1e293b").text("AI-Generated Analysis", { underline: true });
      doc.moveDown(0.5);

      content.narrative.sections.forEach((section) => {
        doc.fontSize(12).fillColor("#4f46e5").text(section.title);
        doc.moveDown(0.2);
        doc.fontSize(11).fillColor("#334155").text(section.body, {
          align: "justify",
          lineGap: 4,
        });
        doc.moveDown(0.8);
      });

      // Recommended Actions
      if (content.narrative.recommendedActions.length > 0) {
        doc.moveDown(0.5);
        doc.fontSize(14).fillColor("#1e293b").text("Recommended Actions", { underline: true });
        doc.moveDown(0.5);

        content.narrative.recommendedActions.forEach((action, index) => {
          doc.fontSize(11).fillColor("#1e293b").text(`${index + 1}. ${action.title}`);
          doc.moveDown(0.1);
          doc.fontSize(10).fillColor("#334155").text(`Priority: ${action.priority}`);
          doc.moveDown(0.1);
          doc.fontSize(10).fillColor("#475569").text(action.rationale, {
            align: "justify",
            lineGap: 3,
          });
          doc.moveDown(0.5);
        });
      }

      // Footer
      const pageCount = doc.bufferedPageRange().count;
      for (let i = 0; i < pageCount; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor("#94a3b8").text(
          `Page ${i + 1} of ${pageCount} | Generated by Project LOOP`,
          72,
          doc.page.height - 36,
          { align: "center" }
        );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
